// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: Protos/docent_service/docent_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - org_sfomuseum_docent_service.DocentService

/// Namespace containing generated types for the "org_sfomuseum_docent_service.DocentService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum OrgSfomuseumDocentService_DocentService: Sendable {
    /// Service descriptor for the "org_sfomuseum_docent_service.DocentService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "org_sfomuseum_docent_service.DocentService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "ParseWallLabel" metadata.
        public enum ParseWallLabel: Sendable {
            /// Request type for "ParseWallLabel".
            public typealias Input = OrgSfomuseumDocentService_ParseWallLabelRequest
            /// Response type for "ParseWallLabel".
            public typealias Output = OrgSfomuseumDocentService_ParseWallLabelResponse
            /// Descriptor for "ParseWallLabel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "org_sfomuseum_docent_service.DocentService"),
                method: "ParseWallLabel"
            )
        }
        /// Namespace for "SummarizeText" metadata.
        public enum SummarizeText: Sendable {
            /// Request type for "SummarizeText".
            public typealias Input = OrgSfomuseumDocentService_SummarizeTextRequest
            /// Response type for "SummarizeText".
            public typealias Output = OrgSfomuseumDocentService_SummarizeTextResponse
            /// Descriptor for "SummarizeText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "org_sfomuseum_docent_service.DocentService"),
                method: "SummarizeText"
            )
        }
        /// Descriptors for all methods in the "org_sfomuseum_docent_service.DocentService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ParseWallLabel.descriptor,
            SummarizeText.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "org_sfomuseum_docent_service.DocentService" service.
    public static let orgSfomuseumDocentService_DocentService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "org_sfomuseum_docent_service.DocentService")
}

// MARK: org_sfomuseum_docent_service.DocentService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService {
    /// Streaming variant of the service protocol for the "org_sfomuseum_docent_service.DocentService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ParseWallLabel" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `OrgSfomuseumDocentService_ParseWallLabelRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `OrgSfomuseumDocentService_ParseWallLabelResponse` messages.
        func parseWallLabel(
            request: GRPCCore.StreamingServerRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>

        /// Handle the "SummarizeText" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `OrgSfomuseumDocentService_SummarizeTextRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `OrgSfomuseumDocentService_SummarizeTextResponse` messages.
        func summarizeText(
            request: GRPCCore.StreamingServerRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<OrgSfomuseumDocentService_SummarizeTextResponse>
    }

    /// Service protocol for the "org_sfomuseum_docent_service.DocentService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: OrgSfomuseumDocentService_DocentService.StreamingServiceProtocol {
        /// Handle the "ParseWallLabel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_ParseWallLabelRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `OrgSfomuseumDocentService_ParseWallLabelResponse` message.
        func parseWallLabel(
            request: GRPCCore.ServerRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>

        /// Handle the "SummarizeText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_SummarizeTextRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `OrgSfomuseumDocentService_SummarizeTextResponse` message.
        func summarizeText(
            request: GRPCCore.ServerRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<OrgSfomuseumDocentService_SummarizeTextResponse>
    }

    /// Simple service protocol for the "org_sfomuseum_docent_service.DocentService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: OrgSfomuseumDocentService_DocentService.ServiceProtocol {
        /// Handle the "ParseWallLabel" method.
        ///
        /// - Parameters:
        ///   - request: A `OrgSfomuseumDocentService_ParseWallLabelRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `OrgSfomuseumDocentService_ParseWallLabelResponse` to respond with.
        func parseWallLabel(
            request: OrgSfomuseumDocentService_ParseWallLabelRequest,
            context: GRPCCore.ServerContext
        ) async throws -> OrgSfomuseumDocentService_ParseWallLabelResponse

        /// Handle the "SummarizeText" method.
        ///
        /// - Parameters:
        ///   - request: A `OrgSfomuseumDocentService_SummarizeTextRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `OrgSfomuseumDocentService_SummarizeTextResponse` to respond with.
        func summarizeText(
            request: OrgSfomuseumDocentService_SummarizeTextRequest,
            context: GRPCCore.ServerContext
        ) async throws -> OrgSfomuseumDocentService_SummarizeTextResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: OrgSfomuseumDocentService_DocentService.Method.ParseWallLabel.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<OrgSfomuseumDocentService_ParseWallLabelRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<OrgSfomuseumDocentService_ParseWallLabelResponse>(),
            handler: { request, context in
                try await self.parseWallLabel(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: OrgSfomuseumDocentService_DocentService.Method.SummarizeText.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<OrgSfomuseumDocentService_SummarizeTextRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<OrgSfomuseumDocentService_SummarizeTextResponse>(),
            handler: { request, context in
                try await self.summarizeText(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService.ServiceProtocol {
    public func parseWallLabel(
        request: GRPCCore.StreamingServerRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<OrgSfomuseumDocentService_ParseWallLabelResponse> {
        let response = try await self.parseWallLabel(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func summarizeText(
        request: GRPCCore.StreamingServerRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<OrgSfomuseumDocentService_SummarizeTextResponse> {
        let response = try await self.summarizeText(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService.SimpleServiceProtocol {
    public func parseWallLabel(
        request: GRPCCore.ServerRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<OrgSfomuseumDocentService_ParseWallLabelResponse> {
        return GRPCCore.ServerResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>(
            message: try await self.parseWallLabel(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func summarizeText(
        request: GRPCCore.ServerRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<OrgSfomuseumDocentService_SummarizeTextResponse> {
        return GRPCCore.ServerResponse<OrgSfomuseumDocentService_SummarizeTextResponse>(
            message: try await self.summarizeText(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: org_sfomuseum_docent_service.DocentService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService {
    /// Generated client protocol for the "org_sfomuseum_docent_service.DocentService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "ParseWallLabel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_ParseWallLabelRequest` message.
        ///   - serializer: A serializer for `OrgSfomuseumDocentService_ParseWallLabelRequest` messages.
        ///   - deserializer: A deserializer for `OrgSfomuseumDocentService_ParseWallLabelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func parseWallLabel<Result>(
            request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            serializer: some GRPCCore.MessageSerializer<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<OrgSfomuseumDocentService_ParseWallLabelResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SummarizeText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_SummarizeTextRequest` message.
        ///   - serializer: A serializer for `OrgSfomuseumDocentService_SummarizeTextRequest` messages.
        ///   - deserializer: A deserializer for `OrgSfomuseumDocentService_SummarizeTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func summarizeText<Result>(
            request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
            serializer: some GRPCCore.MessageSerializer<OrgSfomuseumDocentService_SummarizeTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<OrgSfomuseumDocentService_SummarizeTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_SummarizeTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "org_sfomuseum_docent_service.DocentService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ParseWallLabel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_ParseWallLabelRequest` message.
        ///   - serializer: A serializer for `OrgSfomuseumDocentService_ParseWallLabelRequest` messages.
        ///   - deserializer: A deserializer for `OrgSfomuseumDocentService_ParseWallLabelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func parseWallLabel<Result>(
            request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            serializer: some GRPCCore.MessageSerializer<OrgSfomuseumDocentService_ParseWallLabelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<OrgSfomuseumDocentService_ParseWallLabelResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: OrgSfomuseumDocentService_DocentService.Method.ParseWallLabel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SummarizeText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `OrgSfomuseumDocentService_SummarizeTextRequest` message.
        ///   - serializer: A serializer for `OrgSfomuseumDocentService_SummarizeTextRequest` messages.
        ///   - deserializer: A deserializer for `OrgSfomuseumDocentService_SummarizeTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func summarizeText<Result>(
            request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
            serializer: some GRPCCore.MessageSerializer<OrgSfomuseumDocentService_SummarizeTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<OrgSfomuseumDocentService_SummarizeTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_SummarizeTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: OrgSfomuseumDocentService_DocentService.Method.SummarizeText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService.ClientProtocol {
    /// Call the "ParseWallLabel" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `OrgSfomuseumDocentService_ParseWallLabelRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func parseWallLabel<Result>(
        request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.parseWallLabel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<OrgSfomuseumDocentService_ParseWallLabelRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<OrgSfomuseumDocentService_ParseWallLabelResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SummarizeText" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `OrgSfomuseumDocentService_SummarizeTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func summarizeText<Result>(
        request: GRPCCore.ClientRequest<OrgSfomuseumDocentService_SummarizeTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_SummarizeTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.summarizeText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<OrgSfomuseumDocentService_SummarizeTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<OrgSfomuseumDocentService_SummarizeTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension OrgSfomuseumDocentService_DocentService.ClientProtocol {
    /// Call the "ParseWallLabel" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func parseWallLabel<Result>(
        _ message: OrgSfomuseumDocentService_ParseWallLabelRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_ParseWallLabelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<OrgSfomuseumDocentService_ParseWallLabelRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.parseWallLabel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SummarizeText" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func summarizeText<Result>(
        _ message: OrgSfomuseumDocentService_SummarizeTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<OrgSfomuseumDocentService_SummarizeTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<OrgSfomuseumDocentService_SummarizeTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.summarizeText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}